antvis/mcp-server-chart

package.json, src/index.ts
=> fix: add exec env node

src/index.ts
#5 
add bar historgram scatter word-cloud
=> add bar historgram, scatter, word-cloud

.prettierrc, README.md, src/index.ts
=> feat: add radar

README.md, src/index.ts
=> feat: add treemap chart

README.md, src/index.ts
=> feat: add four graphs

package.json, src/index.ts
- Add axios retry
- Default setting
=> feat: axios retry

src/index.ts
=> feat: version change

README.md
=> docs: add preview image in readme

package.json, src/index.ts
json schema 修改：
- dual-axes（scheme 增加 data 及描述）
- mind-map、flow_diagram、fishbone_diagram、 network_graph （scheme 修改 item 为 items）
=> fix: dual-axes 's data json schema error

README.md, smithery.yaml
[![smithery badge](https://smithery.ai/badge/@antvis/mcp-server-chart)](https://smithery.ai/server/@antvis/mcp-server-chart)
=> docs: add smithery badge

package.json, src/index.ts
修复 scheme 配置
- pie、Radar、mind_map、network_graph、flow_diagram、fishbone_diagram 等 删除 axisXTitle 以及 axisYTitle
- dual_axes_chart 配置 增加 required
- 图片生成接口 增加埋点 key
=> fixed pie's schema - delete axisXTitle and axisYTitle 

.github/workflows/build.yml, .gitignore, README.md, package.json
=> test: fix test case on action

Dockerfile
=> deploy: fix docker file

README.md, claude_desktop_config.json, package.json, src/index.ts, src/server.ts, src/services/index.ts, src/services/sse.ts, src/services/stdio.ts
- fixed: https://github.com/antvis/mcp-server-chart/issues/40
=> feat: support sse transport with cli param, stdio default

src/services/sse.ts, src/services/stdio.ts
- fixed: https://github.com/antvis/mcp-server-chart/issues/48
=> chore: enhance terminal console for SSE with clickable URLs

README.md, package.json
- chore: update deps for debug streamable http
- add emoji for readme
=> chore: update deps for debug streamable http

package.json, src/utils/generate.ts
=> fix: remove retry to fix request error

README.md, __tests__/charts/column.json, __tests__/charts/dual-axes.json, __tests__/charts/word-cloud.json, package.json, src/charts/column.ts, src/charts/dual-axes.ts, src/charts/word-cloud.ts
- add dual-axes series description
- fixed word-cloud data  description
=> feat：fixed charts schema description

README.md
=> docs: update typo

package.json, src/server.ts, tsconfig.json
=> build: export declaration

package.json, src/server.ts
=> chore: 0.5.3

README.md, package.json
1. `generate_area_chart`: Generate an `area` chart, used to display the trend of data under a continuous independent variable, allowing observation of overall data trends.
1. `generate_bar_chart`: Generate a `bar` chart, used to compare values across different categories, suitable for horizontal comparisons.
1. `generate_boxplot_chart`: Generate a `boxplot`, used to display the distribution of data, including the median, quartiles, and outliers.
1. `generate_column_chart`: Generate a `column` chart, used to compare values across different categories, suitable for vertical comparisons.
1. `generate_dual_axes_chart`: Generate a `dual-axes` chart, used to display the relationship between two variables with different units or ranges.
1. `generate_fishbone_diagram`: Generate a `fishbone` …
=> docs: update tool desc and fix alert

__tests__/charts/bar.json, __tests__/charts/column.json, __tests__/charts/dual-axes.json, __tests__/charts/line.json, __tests__/charts/pie.json, __tests__/charts/radar.json, src/charts/bar.ts, src/charts/column.ts, src/charts/dual-axes.ts, src/charts/line.ts, src/charts/pie.ts, src/charts/radar.ts
=> feat: support custom style for 6 charts

__tests__/charts/bar.json, __tests__/charts/column.json, __tests__/charts/dual-axes.json, __tests__/charts/line.json, __tests__/charts/pie.json, __tests__/charts/radar.json, package.json, src/charts/bar.ts, src/charts/column.ts, src/charts/dual-axes.ts, src/charts/line.ts, src/charts/pie.ts, src/charts/radar.ts, src/server.ts
当前提示词，会默认将 ['#1890FF', '#2FC25B'] 作为色板，修改一下。
https://mdn.alipayobjects.com/one_clip/afts/img/oorHTJQXkQwAAAAAROAAAAgAoEACAQFr/original
=> fix palette value

__tests__/charts/histogram.json, package.json, src/charts/histogram.ts
- fixed https://github.com/antvis/mcp-server-chart/issues/155
=> fix: histogram schema
